server:
  port: 9001

eureka:
  instance:
    hostname: discoverEuraka
    instance-id: ${spring.application.name}-${spring.cloud.client.ipAddress}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9001/eureka
      # defaultZone: http://user:password123@localhost:9001/eureka

spring:
  application:
    name: springcloud-discovery-euraka
     
     
      