spring:
  application:
    name: springcloud-hystrix-turbine

server:
  port: 9011

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}  # 将Instance ID设置成IP:端口的形式
