server:
  port: 9021

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
      # defaultZone: http://user:password123@localhost:9001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${spring.cloud.client.ipAddress}:${server.port}}
 
  
spring:
  application:
    name: springcloud-consumer-user-ribbon-properties-customizing
  
springcloud-provide-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
  
  
  
  