spring:
  application:
    name: springcloud-gateway-zuul-reg-exp

server:
  port: 9043

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    prefer-ip-address: true
