spring:
  application:
    name: springcloud-gateway-zuul

server:
  port: 9040

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    prefer-ip-address: true
 
