server:
  port: 9031
  
  
spring:
  application:
    name: springcloud-consumer-user-feign-customizing

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:9001/eureka
      # defaultZone: http://user:password123@localhost:9001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
 
logging:
  level:
    com.vnext.feign.UserFeignClient: DEBUG 

feign.hystrix.enabled: false ## 索性禁用feign的hystrix支持 


  
  
  
  