server:
  port: 9003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
      # defaultZone: http://user:password123@localhost:9001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
 
  
spring:
  application:
    name: springcloud-consumer-user-feign
  


  
  
  
  